apiVersion: apps/v1
kind: Deployment
metadata:
name: my-react-deployments
spec:
replicas: 1
selector:
matchLabels:
app: my-react-deployments
template:
metadata:
labels:
app: my-react-deployments
spec:
containers:
— image: rahuldss88/react_jenkins:latets
name: my-react-app-latestss
imagePullPolicy: Always
ports:
— containerPort: 5000
