apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-deployments
  namespace: default  # Ensure it runs in the default namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-deployments
  template:
    metadata:
      labels:
        app: my-react-deployments
    spec:
      containers:
        - name: my-react-app
          image: rahuldss88/react_jenkins:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
